Fix the object identity issue due to inconsistent import paths of pip._vendor package.
